# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'Biller' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!

  # Pods for Biller
#  pod 'FutureKit'
  pod 'ReactiveSwift', '~> 2.0'
  pod 'RealmSwift'
  pod 'SwiftLint'
  pod 'Result'

  target 'BillerTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'BillerUITests' do
    inherit! :search_paths
    # Pods for testing
  end

end
